class Interval:
    minute_1 = 'minute'
    minute_2 = '2minute'
    minute_3 = '3minute'
    minute_4 = '4minute'
    minute_5 = '5minute'
    minute_10 = '10minute'
    minute_15 = '15minute'
    minute_30 = '30minute'
    hour_1 = '60minute'
    hour_2 = '2hour'
    hour_3 = '3hour'
    hour_4 = '4hour'
    day = 'day'
